services:
    redis:
        image: redis/redis-stack-server:latest
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        healthcheck:
            test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
        volumes:
            - ./docker-data/redis:/data
        env_file:
            - .env
